spring.application.name=photo-album-service
spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/photo_album}
spring.datasource.username=${DB_USERNAME:erinxu}
spring.datasource.password=${DB_PASSWORD:}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true